### ISSUE TITLE
关于合并问题

### ISSUE THREAD

**Issue by ob8102** [xhlove/mpd-content-parser#1]
你好 请问一下
字幕分割成好几段.mp4要怎么合并成一个？
试了很久还是无法合并起来

**Comment by xbstory** [comment]
可以试试这个脚本转换 -> https://github.com/xhlove/dash-mp4-vtt-extractor

或者尝试MP4Box -> https://github.com/nilaoda/Blog/discussions/32

**Comment by ob8102** [comment]
你好 请问一下
我用脚本转换后 字幕会变成有重复行跟重叠在一起的情形
不知道要怎么解决

![WV](https://user-images.githubusercontent.com/75535668/102289212-102e6200-3f79-11eb-9804-5dd52da529d6.jpg)

**Comment by xbstory** [comment]
请提供10-20个连续的mp4样本

**Comment by ob8102** [comment]
麻烦你帮我看一下 谢谢
[dash-0-0-text-WVTT-1.248kbps.zh-TW.zip](https://github.com/xhlove/mpd-content-parser/files/5703249/dash-0-0-text-WVTT-1.248kbps.zh-TW.zip)

**Comment by xbstory** [comment]
从所提供的样本来看，mp4文件中没有足够的信息表明重复行应当同属于同一句话（虽然它们的确是同一句）。

但个人认为通过它们的开始结束时间相同、前后内容一致这两个条件来判断为同一句话还是不妥，所以就不作更多处理了。

虽然重复，但是实际显示字幕是流畅的，并不影响视频观看，所以就这样吧。

**Comment by xbstory** [comment]
建议再试试二进制合并init和后续的mp4文件为单个mp4文件，然后用`MP4Box`提取。

**Comment by ob8102** [comment]
合并后再提取就解决了，非常感谢你，谢谢！
